name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}

    steps:
      # 1. Забираем код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Ставим Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. Генерируем Prisma Client
      # (обязательно до миграций!)
      - name: Generate Prisma Client
        run: npx prisma generate

      # 5. Применяем миграции
      - name: Apply Prisma migrations
        run: npx prisma migrate deploy

      # 6. Сидим базу (опционально)
      - name: Seed database
        run: npx ts-node prisma/seeds/seed.ts

      # 7. Собираем проект
      - name: Build
        run: yarn build
